/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.GestionadorPacientes;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Clases.GestionadorRecuperados;
import Objetos.Paciente;
import Clases.Validaciones;

/**
 *
 * @author Documentos
 */
public class Registro extends javax.swing.JFrame {

    Validaciones v;
    GestionadorPacientes g;

    public Registro() {
        initComponents();
        v = new Validaciones();
        g = new GestionadorPacientes();
        setTitle("Registro de pacientes Covid 19");
        setBounds(650, 350, 570, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textApellidos = new javax.swing.JTextField();
        textNombres = new javax.swing.JTextField();
        textEdad = new javax.swing.JTextField();
        textTemperatura = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        checkTos = new javax.swing.JCheckBox();
        checkCansancio = new javax.swing.JCheckBox();
        checkDolorCabeza = new javax.swing.JCheckBox();
        checkDolorGarganta = new javax.swing.JCheckBox();
        checkPerdidaOlfato = new javax.swing.JCheckBox();
        checkPerdidaGusto = new javax.swing.JCheckBox();
        checkDolorPecho = new javax.swing.JCheckBox();
        checkDificultadRespirar = new javax.swing.JCheckBox();
        buttonAñadir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btVolver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Registro de pacientes Covid 19");

        jLabel3.setText("Nombres: ");

        jLabel4.setText("Apellidos:");

        jLabel5.setText("Edad:");

        jLabel6.setText("Temperatura: ");

        textApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textApellidosKeyTyped(evt);
            }
        });

        textNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNombresKeyTyped(evt);
            }
        });

        textEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textEdadKeyTyped(evt);
            }
        });

        textTemperatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textTemperaturaKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel8.setText("Síntomas:");

        checkTos.setText("Tos Seca");

        checkCansancio.setText("Cansancio");

        checkDolorCabeza.setText("Dolor de cabeza");

        checkDolorGarganta.setText("Dolor de garganta");

        checkPerdidaOlfato.setText("Pérdida del olfato");

        checkPerdidaGusto.setText("Pérdida del gusto");

        checkDolorPecho.setText("Dolor en el pecho");

        checkDificultadRespirar.setText("Dificultad para respirar");

        buttonAñadir.setBackground(new java.awt.Color(153, 255, 153));
        buttonAñadir.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        buttonAñadir.setText("Añadir Paciente");
        buttonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAñadirActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese los datos del paciente:");

        btVolver.setBackground(new java.awt.Color(204, 204, 204));
        btVolver.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        btVolver.setText("Volver");
        btVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverActionPerformed(evt);
            }
        });

        jLabel7.setText("ºC.");

        jLabel9.setText("años.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(textNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(textApellidos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(textTemperatura)
                            .addComponent(textEdad))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel9))))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkDificultadRespirar)
                            .addComponent(checkTos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkDolorCabeza)
                            .addComponent(checkCansancio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkDolorPecho, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkDolorGarganta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkPerdidaGusto)
                            .addComponent(checkPerdidaOlfato)))
                    .addComponent(buttonAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkDificultadRespirar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkTos))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(checkCansancio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(checkDolorCabeza))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(checkDolorGarganta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(checkDolorPecho))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonAñadir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkPerdidaGusto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkPerdidaOlfato)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textApellidosKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == true) {
            evt.consume();
        }
    }//GEN-LAST:event_textApellidosKeyTyped

    private void textNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNombresKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) == true) {
            evt.consume();
        }
    }//GEN-LAST:event_textNombresKeyTyped

    private void textEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textEdadKeyTyped
        char c = evt.getKeyChar();
        if (Character.isAlphabetic(c) == true || c == ' ') {
            evt.consume();
        }
        if (textEdad.getText().length() == 3) {
            evt.consume();
        }
    }//GEN-LAST:event_textEdadKeyTyped

    private void buttonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAñadirActionPerformed

        String NombresString = v.quitaEspacios(textNombres.getText());
        String ApellidosString = v.quitaEspacios(textApellidos.getText());
        String EdadString = textEdad.getText();
        String TemperaturaString = textTemperatura.getText();
        if (!"".equals(NombresString)
                && !"".equals(ApellidosString)
                && !"".equals(TemperaturaString)
                && !"".equals(EdadString)
                && !"".equals(validarChecks())) {
            String texto = "Paciente:\n "
                    + "- " + ApellidosString + " " + NombresString + " de " + EdadString + ".\n"
                    + "Presenta sintomas de:\n"
                    + "- Temperatura: " + TemperaturaString + "\n"
                    + validarChecks();
            if (JOptionPane.showConfirmDialog(this, texto, "Registrar paciente", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {
                g.escritura(new Paciente(NombresString, ApellidosString, EdadString,
                        TemperaturaString, checkDificultadRespirar.isSelected(),
                        checkTos.isSelected(), checkCansancio.isSelected(), checkDolorCabeza.isSelected(),
                        checkDolorGarganta.isSelected(), checkDolorPecho.isSelected(),
                        checkPerdidaGusto.isSelected(), checkPerdidaOlfato.isSelected(), contador()));
            }
        } else {
            JOptionPane.showMessageDialog(this, "Rellene los campos", "Campos vacios", 2);
        }
    }//GEN-LAST:event_buttonAñadirActionPerformed

    private void textTemperaturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTemperaturaKeyTyped
        char c = evt.getKeyChar();
        if (Character.isAlphabetic(c) == true || c == ' ') {
            evt.consume();
        }
        if (textTemperatura.getText().length() == 2) {
            evt.consume();
        }
    }//GEN-LAST:event_textTemperaturaKeyTyped

    private void btVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverActionPerformed
        Principal principal = new Principal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVolver;
    private javax.swing.JButton buttonAñadir;
    private javax.swing.JCheckBox checkCansancio;
    private javax.swing.JCheckBox checkDificultadRespirar;
    private javax.swing.JCheckBox checkDolorCabeza;
    private javax.swing.JCheckBox checkDolorGarganta;
    private javax.swing.JCheckBox checkDolorPecho;
    private javax.swing.JCheckBox checkPerdidaGusto;
    private javax.swing.JCheckBox checkPerdidaOlfato;
    private javax.swing.JCheckBox checkTos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textApellidos;
    private javax.swing.JTextField textEdad;
    private javax.swing.JTextField textNombres;
    private javax.swing.JTextField textTemperatura;
    // End of variables declaration//GEN-END:variables

    private String validarChecks() {
        String text = "";

        if (checkDificultadRespirar.isSelected()) {
            text = text + "- Dificultad para respirar.\n";
        }
        if (checkTos.isSelected()) {
            text = text + "- Tos seca.\n";
        }
        if (checkCansancio.isSelected()) {
            text = text + "- Cansancio.\n";
        }
        if (checkDolorCabeza.isSelected()) {
            text = text + "- Dolor de cabeza.\n";
        }
        if (checkDolorGarganta.isSelected()) {
            text = text + "- Dolor de garganta.\n";
        }
        if (checkDolorPecho.isSelected()) {
            text = text + "- Dolor en el pecho.\n";
        }
        if (checkPerdidaGusto.isSelected()) {
            text = text + "- Perdida del gusto.\n";
        }
        if (checkPerdidaOlfato.isSelected()) {
            text = text + "- Perdida del olfato.\n";
        }
        return text;
    }

    private int contador() {
        int numberPacientes = 0;

        if (checkDificultadRespirar.isSelected()) {
            numberPacientes++;
        }
        if (checkTos.isSelected()) {
            numberPacientes++;
        }
        if (checkCansancio.isSelected()) {
            numberPacientes++;
        }
        if (checkDolorCabeza.isSelected()) {
            numberPacientes++;
        }
        if (checkDolorGarganta.isSelected()) {
            numberPacientes++;
        }
        if (checkDolorPecho.isSelected()) {
            numberPacientes++;
        }
        if (checkPerdidaGusto.isSelected()) {
            numberPacientes++;
        }
        if (checkPerdidaOlfato.isSelected()) {
            numberPacientes++;
        }
        return numberPacientes;
    }

}
